### ISSUE TITLE
[OOA] Lock on goron mountain

### ISSUE THREAD

**Issue by TheZeldaBoss** [jangler/oracles-randomizer#104]
Hello,

I encountered a small problem on my first try with this randomiser : I'm currently stuck. Made everything I was able to do according to EmoTracker, except in one part of the world that I cannot reach yet because I don't have the correct songs on the Harp.
Is it me who missed something or is it a non-handled case ?

My modified rom has name ooarando_3.4.1_3547215a, if it may be useful.

Every items I currently have, except rings, have been marked there.

![randomiserLock](https://user-images.githubusercontent.com/20317520/56437526-153c9900-62e0-11e9-80e2-c80805be905a.png)

**Comment by jangler** [comment]
I saw you got help for this in the Discord, so I'll close.

**Comment by TheZeldaBoss** [comment]
Yeah, I never thought of that, I wanted to remove that issue by myself when I got the answer, but I didn't find any way to do it. Thank you anyway.
