### ISSUE TITLE
Error on warp song OOA

### ISSUE THREAD

**Issue by TheZeldaBoss** [jangler/oracles-randomizer#105]
Hello,

I just found an error on Ages randomiser (maybe it is normal, maybe not) : I'm playing in hard mode and I reached the crescent island, and I found that the warp on north-west section of the island (in present) activates when we play the tune of currents (2nd one in a classic game), and not when we play tune of echoes (1st one)

**Comment by Sparky7198** [comment]
That Portal isn't in the Vanilla Game, Probably added So you could get to the past without going around the entire Island if you didn't have Mermaid's or Dimitri, it has a Sign also that explain's you need Currents for that one specifiacly

**Comment by jangler** [comment]
The portal is modified to only respond to Currents, since going through it via Echoes would be a potential softlock. Maybe I should place two signs instead of one.
