### ISSUE TITLE
Linked Rewards

### ISSUE THREAD

**Issue by Sparky7198** [jangler/oracles-randomizer#106]
Not sure if this is Currently Fixed But i was playing a Linked games of Ages on 3.4.1, i had the Wooden Sword and did the Clock Secret to get an Upgrade, But it gave me Both the Noble and Master sword Right after each other,also the Smithy Secret Just gave me 50 Ruppes instead of the Mirror Shield (I Had the Iron Shield),Transfering it back to Ages however upgraded my Shield Correctly (I couldn't find the Mirror Shield However after that Point so i assume it also got Turned into 50 Ruppes) EDIT: After digging through the game using the Spoiler Log i found the Shield Upgrade and it upgraded Properly to the Mirror Shield,Not sure if this applies if i have the Iron Shield and use the Smithy Secret in Ages though.

**Comment by jangler** [comment]
I think I know why you would have been given two sword upgrades at once in Seasons. That's currently fixed in the dev branch (although it won't be released for a little while).

I don't know linked very well so I'm not sure about the smithy secret, but I'll look into it.

**Comment by Sparky7198** [comment]
The Double Sword Upgrade was Given in Ages,not in Seasons but it might be the other way around if i did a Linked Seasons

**Comment by jangler** [comment]
Sword issue should be fixed for both games in db88e5e. In 3.5 it should actually be fine in Seasons, but not Ages.

**Comment by Sparky7198** [comment]
(Been a while since i played a run of this Lol) Yeah the Double Sword Upgrade if you had the Wooden Sword and used a Sword Secret is Fixed but the Smithy Secret by playing Linked Ages is still broken, i assume it has to do something with the Hard Ore upgrading the Shield Specifiacly since in one seed it gave me a Ribbon for it,then i did the Smithy Secret and it gave me Another Ribbon. [The Shield Transfers over to Ages Properly. its just Seasons)

**Comment by jangler** [comment]
I think the randomizer code is written to ignore the status of your shield so that it gives you the same item regardless of whether you have it or what level it is, and I guess the linked secret code uses the same routine that the normal hard ore upgrade uses.

**Comment by Sparky7198** [comment]
Probably. Oh well, if the Shield Transfers over to Ages its fine Since there isn't much to do in Post-game Seasons.
