### ISSUE TITLE
Is Energy Ring/Light Ring With Noble/Master Sword Required?

### ISSUE THREAD

**Issue by Sparky7198** [jangler/oracles-randomizer#107]
Just Noticed That Gohma Is Beatable without Seeds in Seasons if you use Sword Beam's with the Energy Ring or The Upgraded Sword's. is that in Logic? (Im not Sure if you need Scent Seeds, i tried with other types but it didn't seem to Work)

**Comment by jangler** [comment]
Gohma without seeds isn't in logic since Gohma is locked behind Agunima (the miniboss), who strictly requires ember seeds.

Ember seeds and scent seeds damage Gohma; mystery seeds have a 1 in 4 chance.
