### ISSUE TITLE
Color Patching in the Program?

### ISSUE THREAD

**Issue by Sparky7198** [jangler/oracles-randomizer#108]
Its Rather Annoying to make a Rom just to patch it out using the Web Rando if you want to change Link's tunic Color

**Comment by jangler** [comment]
I know a lot of randomizers have a lot of options for purely aesthetic changes, but I personally see that as being beyond the intended scope of oracles-randomizer, and a potential rabbit hole. Also, in case it's not clear, I'm not affiliated with the web interface – that's entirely jaysee87.
