### ISSUE TITLE
Unobtainable Key in Hero's Cave (OoS)

### ISSUE THREAD

**Issue by SporyTike** [jangler/oracles-randomizer#109]
I started the randomizer for the first time and went to Hero's Cave. I got the first chest (which normally has the key) and the one you reach when falling in the hole. Both didn't had the key in it so I couldn't reach the last chest which needs the key. I know that the last chest must have the key so I can skip it but I think that means there is an issue with the randomization of the chest at least in the Hero's Cave.

Version: 4.0.1
Seed: 7F861399+TP
Model: Marin
Tree Warp enabled
Shuffle Portals enabled
I used the web randomizer for the game.

**Comment by jangler** [comment]
The randomizer considers it OK for unnecessary items to be inaccessible. Small keys are the most common example, but in hard logic even the cape can be self-locked, since it's not strictly required to beat the game.
