### ISSUE TITLE
Incompletable seed, missing logic (D8 Ages)

### ISSUE THREAD

**Issue by Scotfree2** [jangler/oracles-randomizer#111]
I ended up with an incompletable seed in Oracle of ages seed 9fed2e08-t (tree warp on, hard mode off, dungeon shuffle off). In it, I am required to get to the D8 Tile Room in order to obtain a trade sequence item required in order to get the Power Glove. However, since I don't have the Power Glove, I cannot make it to the Tile Room as it requires picking up the statue that requires the Power Glove.
There is no way I know of to allow the minecart to get into the Tile Room without using the Power Glove to go to D3, then ascend the other staircase to push the cube and unlock the minecart path. The current logic does not have the Power Glove as a prerequisite for the Tile Room or SE Slate chest, but I believe that it is a requirement.

**Comment by raekuul** [comment]
Spoiler Log snippet for reference.
```
sphere 15:
D8 SE slate chest            <- crown key
D8 tile room                 <- brother emblem

sphere 16:
trade rock brisket           <- lava juice

sphere 17:
trade lava juice             <- power bracelet/glove
```

**Comment by jangler** [comment]
Thanks, I'll merge the fix tomorrow.
