### ISSUE TITLE
[4.0.8] Softlock in Moblin's keep in OOA

### ISSUE THREAD

**Issue by Batro** [jangler/oracles-randomizer#127]
[ooarando_4.0.8_35578cb4-td_log.txt](https://github.com/jangler/oracles-randomizer/files/4239275/ooarando_4.0.8_35578cb4-td_log.txt)

I got to Moblin's keep using the L-1 hookshot, the song of Time and the Flower Bomb, fell into the basement, but cannot go out of it with my current equipment (shown in screenshot), except by dying, the Roc Feather is required.

![Current equipment](https://user-images.githubusercontent.com/9999909/75091474-f6e1a280-556d-11ea-9d09-b40d4d8335a8.PNG)

**Comment by jangler** [comment]
You can save and quit to get out.
