### ISSUE TITLE
Create ROM using pre-defined seed

### ISSUE THREAD

**Issue by riftrsps** [jangler/oracles-randomizer#128]
I have a couple seeds saved, but I can not find any way to create a ROM using the seeds.

It seems the only way to create a new randomized ROM is to create a new seed.

**Comment by ReggX** [comment]
There is, see the example image.

![image](https://user-images.githubusercontent.com/1953510/76710569-e1910b80-6708-11ea-90fb-12c240fa9c2a.png)
