### ISSUE TITLE
Plugging In Seed Not Working

### ISSUE THREAD

**Issue by TimeKnight13** [jangler/oracles-randomizer#137]
My wife and I wanna race the randomizer for Ages, but whenever we want to use a specific seed to do so to make it fair, it still pulls up a random seed and uses that instead. :c

**Comment by jangler** [comment]
Looks like this broke in 4.1 because of some multiworld-related restructuring (the `-seed` flag still works, but the interactive prompt doesn't). As a workaround I suggest just generating one ROM and sharing that, if possible.

**Comment by jangler** [comment]
Fixed in 4.1.2.
