### ISSUE TITLE
Go generate failing

### ISSUE THREAD

**Issue by Berserker66** [jangler/oracles-randomizer#145]
Followed the instructions https://github.com/jangler/oracles-randomizer/blob/master/doc/contributing.md on a windows 10 computer and when running go generate I get:

```
panic: error getting import path from working directory

goroutine 1 [running]:
main.generateMain()
        E:/ROMS/Randomizer/Oracles/generate/generate.go:55 +0x18b
main.main()
        E:/ROMS/Randomizer/Oracles/generate/generate.go:43 +0x27
exit status 2
generate.go:8: running "go": exit status 1
```

**Comment by ReggX** [comment]
You did not follow the instrcutions correctly.

The git repo should be located in $GOPATH/src/github.com/jangler/oracles-randomizer, not E:/ROMS/Randomizer/Oracles/

generate.go requires strict adherence to the path naming convention.

**Comment by Berserker66** [comment]
```
E:\ROMS\Randomizer\Oracles>go get github.com/jangler/oracles-randomizer
# github.com/jangler/oracles-randomizer
runtime.main_main·f: function main is undeclared in the main package

E:\ROMS\Randomizer\Oracles>cd $GOPATH/src/github.com/jangler/oracles-randomizer
The system cannot find the path specified.
```

**Comment by ReggX** [comment]
Did you set up your GOPATH correctly?

https://github.com/golang/go/wiki/SettingGOPATH

**Comment by Berserker66** [comment]
![image](https://user-images.githubusercontent.com/3189725/86522237-1b725300-be5b-11ea-9ed7-56571a7b6768.png)

**Comment by ReggX** [comment]
oh yeah, Windows environment variable handling...

Try  `cd /d %GOPATH%/src/github.com/jangler/oracles-randomizer` instead

**Comment by Berserker66** [comment]
I got there manually. I'm using GoLand anyway, so I had to navigate there anyway.

**Comment by jangler** [comment]
The `go generate` code that runs for the randomizer assumes the path to the repository matches `github.com/(.+)/oracles-randomizer`, since a properly configured Go environment would place it there.
