### ISSUE TITLE
might be me, but running through Lua on Debian Buster calls syntax errors

### ISSUE THREAD

**Issue by cj0516** [jangler/oracles-randomizer#146]
I might be the only one with this problem, but anytime i open the terminal and attempt to run the rando, it gives me this:

``` debian
 goose@penguin:~$ cd ~/"oos-ooa rando"
 goose@penguin:~/oos-ooa rando$ lua Oracles.lua
 lua: Oracles.lua:59: attempt to index a nil value (global 'memory')
 stack traceback:
        Oracles.lua:59: in main chunk
        [C]: in ?
```

The first line is just to open the folder containing it and then run it in the next. For reference, the .gbc file is named "TheLegendofZelda-OracleofSeasons.gbc." Is this the problem, or can Debian Buster not run the file?

Thanks in advance!

**Comment by cj0516** [comment]
Renamed file, init lua and rando, this happened.

```debian
goose@penguin:~/oos-ooa rando$ lua
Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio
> "Oracles.lua"
Oracles.lua
> oos.gbc "oosm.gbc"
stdin:1: attempt to index a nil value (global 'oos')
stack traceback:
        stdin:1: in main chunk
        [C]: in ?
> 
``` 
Still figuring it out.

**Comment by Drenn1** [comment]
That's not the randomizer, that's the lua script for multiworld with bizhawk. If you want to build the randomizer yourself, see contributing.md: https://github.com/jangler/oracles-randomizer/blob/master/doc/contributing.md
