### ISSUE TITLE
"d4 color tile drop" problem with hard logic

### ISSUE THREAD

**Issue by Drenn1** [jangler/oracles-randomizer#155]
This logic appears to be for the long minecart room in Ages D4 where you need to kill 3 stalfos.

```
d4 color tile drop: [d4 minecart C,
    or: [sword, ember seeds, scent shooter, gale shooter,
        [hard, scent satchel]]]
```

As far as I can tell, the only reason "scent satchel" is included in hard logic (as opposed to ember/mystery satchel) is the assumption that the stalfos are attracted to scent seeds; but this isn't the case. Since they aren't, you would need to wait for the stalfos to approach the wall and then hit them with almost pixel-perfect precision with scent seeds. This takes an eternity. So my suggestion would be to remove this from hard logic, unless I'm missing something.

**Comment by Drenn1** [comment]
Actually, I seem to have misread the logic... ember seeds are in normal logic because they're easier to use. I guess this wasn't unintentional. But I find this incredibly difficult to do even when using speedups to wait for the stalfos to approach.

**Comment by jangler** [comment]
I agree, this seems unnecessarily mean. Logic changes that aren't bugs normally go to `dev`, but this can go to `patch` since it's obscure and makes things easier rather than harder and `dev` may never get merged.

**Comment by Drenn1** [comment]
Cool. As for using the ember satchel which remains in logic, I'm tempted to either move that into hard logic or remove it altogether. Certainly it's easier, but it still depends on hoping the skeletons move into it.
