### ISSUE TITLE
Can't find Yoll Graveyard key, anywhere!

### ISSUE THREAD

**Issue by 03bgood** [jangler/oracles-randomizer#158]
I have all dungeon items except Lv. 1's and to do that, I need the Yoll Graveyard key and I haven't found it, anywhere and I've pretty much found almost everything. My seed is: BODA62CC+T

Where can I find a list of item pickup spots for both OOS&OOA? Maybe I've missed something.

**Comment by jangler** [comment]
- Downloads of randomizer releases from GitHub include a HTML checklist of item locations
- If you ran the randomizer yourself, a "spoiler log" text file with all locations is also generated
- There is an EmoTracker plugin for Oracles randomizer

**Comment by 03bgood** [comment]
Found it.
