### ISSUE TITLE
Seasons: Magic Boomerang unreacheable without glitch

### ISSUE THREAD

**Issue by Cesar-rso** [jangler/oracles-randomizer#160]
The magic boomerang ended up in the cave in the Spool Swamp, next to dungeon 2. The thing is that the cave is blocked by mushrooms, and the default season for the area is winter. Because of how the map is laid out, the treasure chest in that cave is unreacheable unless the default season is Autumn or Summer (the tree stump is only reacheable climbing the vines) 
[oosrando_4.1.6_b738b1e2-d_log.txt](https://github.com/jangler/oracles-randomizer/files/12138820/oosrando_4.1.6_b738b1e2-d_log.txt)

**Comment by jangler** [comment]
In this seed, you can use Ricky to jump up the cliff and reach the tree stump.

**Comment by Cesar-rso** [comment]
My bad, forgot about Ricky's ability
