### ISSUE TITLE
Linked game issues

### ISSUE THREAD

**Issue by jangler** [jangler/oracles-randomizer#54]
The randomizer was never intended to support linked games, but linked support has been requested and it might be satisfied by:

- Keeping Hero's Cave as the unlinked version
- Something about the Maku Tree doing a different script and not dropping an item
- Looking at the jewel chests that are different

**Comment by raekuul** [comment]
Ages also requires a solution to the Ambi's Tower Hijack that occurs in vanilla linked after D3.

**Comment by jangler** [comment]
Linked things are "done" but not integration-tested; 3.3 will support linked in a "beta" capacity.
