### ISSUE TITLE
[Request] Randomize Red Ring

### ISSUE THREAD

**Issue by WashedUpLinkshot** [jangler/oracles-randomizer#59]
As much as I hate myself for even suggesting this, I think it would be cool to have to slay the 4 Golden Beasts to open up an item location, and to have the Red Ring just sitting around somewhere as a result.

**Comment by jangler** [comment]
This is something I've thought about, along with other non-essential NPC gifts, like the gasha seed from the mayor, the L-2 ring box from the goron, and the sign ring from the sign-loving Subrosian. But it's just *way* more work than any of the other checks, and more often than not you're likely to get a non-progression item for your trouble.

**Comment by WashedUpLinkshot** [comment]
is the brunt of the work in making infallible logic, or in getting the NPC to behave properly? I'm trying to think of the requirements for it off the top of my head:

- Access to Spool Swamp South in Summertime (via Flippers from east w/ default Summer, or same requirements as D3 Completion)
- West Coast Default Spring or Bell Quest + Spring
- Mystery Cave Access without need to clear mushrooms or cross gaps
- Four Jewels + Summer + Winter
- North Horon in Summer

The minimum requirement of total items would be:

- Bracelet
- Flippers
- Summer
- Winter
- Ember Seeds
- Four Jewels

Does that sound right?

(p.s. Sign Ring just sounds like a lot of grinding and is probably the one prize I would advocate not randomizing, unless the requirement is changed to "Destroy 1 Sign")

**Comment by jangler** [comment]
I didn't mean it would be difficult to implement. The brunt of the work would fall on the players ;)

**Comment by WashedUpLinkshot** [comment]
I had a seed the other day with Gnarled Key in pre-Hyper D8, and Dragon Key in D6 blocking L2Boom, so I can't imagine simply routing the Golden Beasts being much more work :P I would love the jewels to be more independent than absolutely needing all 4 seasons to mean anything, as well.

**Comment by raekuul** [comment]
I'd argue that allowing progression behind Red Ring and 100 Signs would need to be opt-in options rather than default ones - Red Ring because it has onerous requirements, 100 Signs because you're adding a useless item into the pool.

**Comment by jangler** [comment]
I'm going to close this for now since it's been months and I still have no particular plans to include new PoH / gasha seed / ring checks. If this happens, it will be part of a 4.x update.
