### ISSUE TITLE
Seed Satchel with "9 L-" pegasus seeds crashes game

### ISSUE THREAD

**Issue by amberflemingf** [jangler/oracles-randomizer#80]
ran into this seed where when i obtained the seed satchel, it had a gliched value of seeds. also had an earlier seed where the seed shooter in the cart minigame had the same, but it didn't crash and i didn't think to report it/keep the log file.

using retroarch with Gambatte core, if that matters.

[ooar_log.txt](https://github.com/jangler/oracles-randomizer/files/2609321/ooar_log.txt)

**Comment by jangler** [comment]
When and how exactly did the game crash?

**Comment by amberflemingf** [comment]
was beside the dirt pile on lynna shore, i equipped it to B and the sprites slowly glitched up and disappeared on the screen and game stopped responding.

**Comment by jangler** [comment]
Closing this since there's been no further info.
