### ISSUE TITLE
Mystery Seeds

### ISSUE THREAD

**Issue by HaukohlR** [jangler/oracles-randomizer#90]
This didn't prevent my completion of the seed, but I thought I should bring up that I was able to get mystery seeds before I think I was intended to in logic from Frypolar's room in D8 from the respawnig grass.  doesn't really matter too much, but you might want to consider it in logic. (This is in seasons btw)

**Comment by jangler** [comment]
It's known but never required in normal difficulty. Hard difficulty sometimes requires it.
