### ISSUE TITLE
Softlock in Nuun

### ISSUE THREAD

**Issue by Scotfree2** [jangler/oracles-randomizer#93]
This softlock can be avoided if you don't Save/Quit at a certain point as I just did in a seed.

Situation: The first few items gave me only Tune of Currents, I checked the cave in Nuun Highlands (Moosh) before I rescued the 3 bridge builders. After rescuing them and being near the bridge, I S+Q'd. This meant that when I started the game, I was at the cave in Nuun Highlands with only Echoes+Currents and thus no way to go back to the past or leave the area.

Solutions possible? Put an Echoes portal outside of the cave OR just put a warning not to save+quit in this situation.

**Comment by jangler** [comment]
Yeah, this has actually been known for a while, but because it's in Nuun, there isn't a technically easy way to fix it without changing logic. Putting a portal there is pretty clearly the ideal solution, though.
