### ISSUE TITLE
Missing item and potential softlock when fixing Tuni Nut before getting item from brothers

### ISSUE THREAD

**Issue by OmegaZeron** [jangler/oracles-randomizer#95]
If you fix the Tuni Nut before talking to the brothers where you get it in vanilla, they will refuse to give you an item, which can cause softlocks (like my run where they were keeping the Flippers from me)

**Comment by jangler** [comment]
Weird, the randomizer has code specifically to address that problem. Guess there's some other variable that needs to be accounted for.

**Comment by OmegaZeron** [comment]
Here's a video of a race I was doing at the time. I'm the smaller screen in the top left, and timestamped to when you can see what happens. I talk to the girls, who just say "Now the volcano should calm down" like normal after putting the Tuni Nut back in place, but the husbands still say "I wish Patch would come at a time like this" but refuse to give the item because the girls don't trigger the sequence anymore

https://www.twitch.tv/videos/383042524?t=01h36m
