### ISSUE TITLE
Second Subrosia trade blocked by ember seed location

### ISSUE THREAD

**Issue by RhinoKneel** [jangler/oracles-randomizer#97]
This is a hard mode seed for Seasons

The log states in sphere 6 that you should pick up the Magnetic Gloves through the second trade in the Subrosia Market. This trade requires both 20 ore chunks and 10 ember seeds. This is impossible at this point, as ember seeds are only located in Tarm Ruins.

[oosrando_3.3.6_c7e1f57c_hard_log.txt](https://github.com/jangler/oracles-randomizer/files/2898342/oosrando_3.3.6_c7e1f57c_hard_log.txt)

**Comment by jangler** [comment]
You can get ember seeds from the chest in D5, which is in hard logic.
