### ISSUE TITLE
Stuck in Woods of Winter

### ISSUE THREAD

**Issue by mysterypaint** [jangler/oracles-randomizer#99]
Hello! I think I might have softlocked in the Woods of Winter: I can't get back to town because I don't have the seed satchel, and I can't escape the woods because I don't have the Spring blessing for the Rod of Seasons.

I've attached my .sav, spoiler .txt log, and seed (.ips) here:

[oosrando_3.3.7_606fe74c_hard.zip](https://github.com/jangler/oracles-randomizer/files/3041304/oosrando_3.3.7_606fe74c_hard.zip)

**Comment by jangler** [comment]
You jumped down from Natzu / Sunken, right? The game should have given you a warning before doing that—the warning means that you could potentially (but not necessarily) softlock if you set a save point after jumping down. Maybe that was unclear?

In any case, yes, you are softlocked as far as I can tell.
